---
- name: Scan and remediate Alma Linux 10 servers
  ansible.builtin.command: |
    oscap xccdf eval
    --profile {{ oscap.xccdf_profile }}
    --fetch-remote-resources
    --skip-rule xccdf_org.ssgproject.content_rule_sudo_require_authentication
    --remediate
    {{ oscap.ds_file }}
  register: oscap_remediation
  changed_when: oscap_remediation.rc == 2
  failed_when: oscap_remediation.rc not in [0, 2]

- name: Remove NOPASSWD entries from /etc/sudoers
  ansible.builtin.replace:
    regexp: (^(?!#).*[\s]+NOPASSWD[\s]*\:.*$)
    replace: '# \g<1>'
    path: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s

- name: Find /etc/sudoers.d/ files
  ansible.builtin.find:
    paths:
      - /etc/sudoers.d/
  register: sudoers

- name: Remove lines containing NOPASSWD from files in /etc/sudoers.d/, excluding the ansible user
  ansible.builtin.replace:
    regexp: (^(?!#).*[\s]+NOPASSWD[\s]*\:.*$)
    replace: '# \g<1>'
    path: "{{ item.path }}"
    validate: /usr/sbin/visudo -cf %s
  loop: "{{ sudoers.files | reject('search', '/etc/sudoers.d/90-cloud-init-users') | list }}"